
#
# qcli_demo setting for Memroy KPI
#
CONFIG_QCCSDK_DEMO=y
CONFIG_QCCSDK_CONSOLE=y
CONFIG_FLASH_SHELL=y
CONFIG_FREERTOS_PLUS_POSIX=y

CONFIG_WIFI_SHELL=y
CONFIG_WLAN_QAPI=y
CONFIG_PLATFORM_SHELL=y
CONFIG_LOWPOWER_SHELL=y
CONFIG_UNITTEST_SHELL=y
CONFIG_I2CM_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_NET_SHELL=y
CONFIG_UART_SHELL=n
CONFIG_LWIP_HEAP_POOL=y
CONFIG_6GHZ=y
CONFIG_6G_BAND=y
CONFIG_RTT_VIEW_CLI=n

CONFIG_WATCH_DOG_ENABLE=n
CONFIG_WATCH_DOG_BARK_TIME=4
CONFIG_WATCH_DOG_BITE_TIME=5
CONFIG_FW_UPGRADE=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_POSIX_FS_API=y
CONFIG_FS_SHELL=y
CONFIG_MPU_DEMO=y
CONFIG_MQTT_CLIENT=y
CONFIG_MQTT_CLIENT_DEMO=n
#CONFIG_SIGMA_TRAFFIC=n
CONFIG_RING_IF_ONLY=n
CONFIG_QCSPI_HFC_TEST=n
CONFIG_QCSPI_HFC_ETH_ENABLE=n
CONFIG_HTTP_CLIENT=y
CONFIG_HTTP_CLIENT_DEMO=y
CONFIG_MGMT_FILTER_DEMO=y
CONFIG_RNG_TEST=y
CONFIG_SNTP_CLIENT=y
CONFIG_SNTP_CLIENT_DEMO=n
CONFIG_ACK_TIMEOUT_MODIFY_ENABLE=y
#CONFIG_SRRC_BAND_EDGE_SUPPORT=n
#CONFIG_HEAVY_CLIP_ENABLE=n
#CONFIG_HEAVY_CLIP_LEVEL_2G=0
#CONFIG_HEAVY_CLIP_LEVEL_5G=0

CONFIG_MBEDTLS_AES_ALT=n
CONFIG_MBEDTLS_CCM_ALT=n
CONFIG_MBEDTLS_SHA_ALT=n
CONFIG_WPS=y
CONFIG_WPS_LIB=y
CONFIG_ENABLE_P2P_MODE=n
CONFIG_ENABLE_P2P_LIB=n
CONFIG_LWIP_MULTIPLE_STREAMS=n
CONFIG_SECUREFS_DEMO=y

CONFIG_XO_USE_BDF_OVERRIDE=n
CONFIG_SAT_STEP_MANUAL_ADJUSTMENT=n
# CONFIG_SAT_STEP_2G_SS=0x00000060
# CONFIG_SAT_STEP_2G_TT=0x00000060
# CONFIG_SAT_STEP_2G_FF=0x00000064
# CONFIG_SAT_STEP_5G_SS=0x00000064
# CONFIG_SAT_STEP_5G_TT=0x00000064
# CONFIG_SAT_STEP_5G_FF=0x00000064

# end of qcli_demo setting
