image_name="FERMION_VCNL3020_TEST_DEMO"
build_id="999"
is_sdk=true
CHIP_VERSION_FERMION=2
board_name="mqm730i"
CONFIG_QCCSDK_BOARD_NAME="mqm730i"
CONFIG_BOARD_MQM730I=true
CONFIG_SOC_QCC730_HAS_UART_V2=true
CONFIG_SOC_QCC730_HAS_XPA_AUTO_CTRL=true
CONFIG_SOC_QCC730_HAS_BT_COEX=true
CONFIG_SOC_QCC730_HAS_I2C=true
CONFIG_SOC_QCC730_HAS_QSPI_V2=true
CONFIG_SOC_QCC730_HAS_SPI_SLAVE=true
CONFIG_BOARD_QCC730_I2C_ENABLE=true
CONFIG_BOARD_QCC730_QSPI_ENABLE=true
CONFIG_BOARD_QCC730_QSPI_V2_QUAD_MODE=1
CONFIG_BOARD_QCC730_UART_ENABLE=true
CONFIG_BOARD_QCC730_UART_GPIO_OPTION=1
CONFIG_BOARD_QCC730_GPIO_DEFAULT_PU_STATE=715530
CONFIG_BOARD_QCC730_GPIO_DEFAULT_PD_STATE=1381616
CONFIG_SOC_QCC730V2=true
CONFIG_QCCSDK_DEMO=true
CONFIG_WLAN_QAPI=true
CONFIG_LOWPOWER_SHELL=true
CONFIG_PLATFORM_QAPI=true
CONFIG_WMI_EVENT=true
CONFIG_WFM_EN=true
CONFIG_6G_BAND=true
CONFIG_MQTT_CLIENT=true
CONFIG_QCCSDK_CONSOLE=true
CONFIG_PBL_PREES_GPIO_RESTORE=true
CONFIG_PBL_PREES_RESET_FOR_DTIM=true
CONFIG_CPR_ENABLE=true
CONFIG_QTMR_GRAY_CODING_WAR=true
CONFIG_ULP_SMPS2_ONTSHOT_OPTIMIZE=true
CONFIG_PMU_TS_MON_PERIOD_US=1000000
CONFIG_PRINTF_ERR=true
CONFIG_PRINTF_WARN=true
CONFIG_PRINTF_INFO=true
CONFIG_ERROR_PREFIX="[ERR]"
CONFIG_WARN_PREFIX="[WARN]"
CONFIG_INFO_PREFIX="[INFO]"
CONFIG_LOG_PREFIX="[LOG]"
CONFIG_DUMP_PREFIX="[DUMP]"
CONFIG_WIFI_FW_RAMDUMP_PRINT_FLAG=0
CONFIG_MPU_ENABLE=true
CONFIG_FERM_MPU_0_START=0
CONFIG_FERM_MPU_0_SIZE=1048576
CONFIG_FERM_MPU_0_XN=1
CONFIG_FERM_MPU_0_ACCESS=3
CONFIG_FERM_MPU_0_SUBREGION=224
CONFIG_FERM_MPU_1_START=0
CONFIG_FERM_MPU_1_SIZE=65536
CONFIG_FERM_MPU_1_XN=0
CONFIG_FERM_MPU_1_ACCESS=6
CONFIG_FERM_MPU_1_SUBREGION=0
CONFIG_FERM_MPU_2_START=65536
CONFIG_FERM_MPU_2_SIZE=32768
CONFIG_FERM_MPU_2_XN=0
CONFIG_FERM_MPU_2_ACCESS=6
CONFIG_FERM_MPU_2_SUBREGION=192
CONFIG_FERM_MPU_3_START=0
CONFIG_FERM_MPU_3_SIZE=0
CONFIG_FERM_MPU_3_XN=0
CONFIG_FERM_MPU_3_ACCESS=0
CONFIG_FERM_MPU_3_SUBREGION=0
CONFIG_FERM_MPU_4_START=2097152
CONFIG_FERM_MPU_4_SIZE=2097152
CONFIG_FERM_MPU_4_XN=0
CONFIG_FERM_MPU_4_ACCESS=6
CONFIG_FERM_MPU_4_SUBREGION=192
CONFIG_FERM_MPU_5_START=2097152
CONFIG_FERM_MPU_5_SIZE=524288
CONFIG_FERM_MPU_5_XN=1
CONFIG_FERM_MPU_5_ACCESS=3
CONFIG_FERM_MPU_5_SUBREGION=224
CONFIG_FERM_MPU_6_START=3604480
CONFIG_FERM_MPU_6_SIZE=65536
CONFIG_FERM_MPU_6_XN=1
CONFIG_FERM_MPU_6_ACCESS=3
CONFIG_FERM_MPU_6_SUBREGION=31
CONFIG_FERM_MPU_7_START=0
CONFIG_FERM_MPU_7_SIZE=1024
CONFIG_FERM_MPU_7_XN=1
CONFIG_FERM_MPU_7_ACCESS=3
CONFIG_FERM_MPU_7_SUBREGION=7
CONFIG_SBL_MPU_0_START=0
CONFIG_SBL_MPU_0_SIZE=1048576
CONFIG_SBL_MPU_0_XN=1
CONFIG_SBL_MPU_0_ACCESS=3
CONFIG_SBL_MPU_0_SUBREGION=224
CONFIG_SBL_MPU_1_START=524288
CONFIG_SBL_MPU_1_SIZE=32768
CONFIG_SBL_MPU_1_XN=0
CONFIG_SBL_MPU_1_ACCESS=6
CONFIG_SBL_MPU_1_SUBREGION=0
CONFIG_SBL_MPU_2_START=2097152
CONFIG_SBL_MPU_2_SIZE=2097152
CONFIG_SBL_MPU_2_XN=1
CONFIG_SBL_MPU_2_ACCESS=3
CONFIG_SBL_MPU_2_SUBREGION=192
CONFIG_SBL_MPU_3_START=2097152
CONFIG_SBL_MPU_3_SIZE=32768
CONFIG_SBL_MPU_3_XN=0
CONFIG_SBL_MPU_3_ACCESS=6
CONFIG_SBL_MPU_3_SUBREGION=0
CONFIG_SBL_MPU_4_START=2129920
CONFIG_SBL_MPU_4_SIZE=8192
CONFIG_SBL_MPU_4_XN=0
CONFIG_SBL_MPU_4_ACCESS=6
CONFIG_SBL_MPU_4_SUBREGION=1
CONFIG_SBL_MPU_5_START=0
CONFIG_SBL_MPU_5_SIZE=0
CONFIG_SBL_MPU_5_XN=0
CONFIG_SBL_MPU_5_ACCESS=0
CONFIG_SBL_MPU_5_SUBREGION=0
CONFIG_SBL_MPU_6_START=0
CONFIG_SBL_MPU_6_SIZE=0
CONFIG_SBL_MPU_6_XN=0
CONFIG_SBL_MPU_6_ACCESS=0
CONFIG_SBL_MPU_6_SUBREGION=0
CONFIG_SBL_MPU_7_START=0
CONFIG_SBL_MPU_7_SIZE=0
CONFIG_SBL_MPU_7_XN=0
CONFIG_SBL_MPU_7_ACCESS=0
CONFIG_SBL_MPU_7_SUBREGION=0
CONFIG_MBEDTLS_USE_PKA=true
CONFIG_MBEDTLS_PKA_TEST=true
CONFIG_NT_DEVCFG_LOCATION_TYPE=1
CONFIG_NT_DEVCFG_LOCATION=0
CONFIG_NT_DEVCFG_FTM_MODE=1
CONFIG_NT_DEVCFG_ASAP=1
CONFIG_NT_DEVCFG_FTM_PER_BURST=2
CONFIG_NT_DEVCFG_NO_OF_BUR_EXP=2
CONFIG_NT_DEVCFG_FTM_MIN_DELTA_RESP=1
CONFIG_NT_DEVCFG_FTM_BURST_DURATION_RESP=10
CONFIG_NT_DEVCFG_FTM_BURST_PERIOD_RESP=40
CONFIG_NT_DEVCFG_FORMAT_AND_BANDWIDTH=0
CONFIG_NT_DEVCFG_PARTIAL_TSF_TIME_OFFSET_RESP=5
CONFIG_NT_DEVCFG_PARTIAL_TSF_TIMER_NO_PREFERENCE_INITIATOR=1
CONFIG_NT_DEVCFG_FTM_MIN_DELTA_INITIATOR=0
CONFIG_NT_DEVCFG_FTM_BURST_DURATION_INITIATOR=15
CONFIG_NT_DEVCFG_FTM_BURST_PERIOD_INITIATOR=0
CONFIG_NT_DEVCFG_WIFI_ON_ENABLE=0
CONFIG_NT_DEVCFG_XPA_ENABLE=0
CONFIG_WIFILIB_6GHZ=true
CONFIG_ACK_TIMEOUT_MODIFY_ENABLE=true
CONFIG_QOS_NULL_DATA_MAX_RETRY_COUNT=10
CONFIG_QOS_NULL_DATA_RETRY_DELAY=100
CONFIG_SRRC_BAND_EDGE_SUPPORT=true
CONFIG_TOTAL_BEACON_WAIT_TIME=25000
CONFIG_WLAN_8021X_LIB=true
CONFIG_QAT_TRANSMISSION_MODULE=0
CONFIG_QAT_CB_SIZE_MTU_MULTIPLIER=10
CONFIG_QAT_CB_QUEUE_MAX_LENGTH=10
