/*
 * Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

#define VISIBLE_HEADER_VERSION_1 1
#define CURRENT_VISIBLE_HEADER_VERSION (VISIBLE_HEADER_VERSION_1)

#define SECUREFS_HMAC_TYPE_NULL 0
#define SECUREFS_HMAC_TYPE_SHA256 1
#define SECUREFS_HMAC_TYPE_AES256_CMAC 2

#define SECUREFS_CIPHER_TYPE_NULL 0
#define SECUREFS_CIPHER_TYPE_AES128_CBC 1
#define SECUREFS_CIPHER_TYPE_AES128_CTR 2
#define SECUREFS_CIPHER_TYPE_AES256_CBC 3
#define SECUREFS_CIPHER_TYPE_AES256_CTR 4

#define SECUREFS_HMAC_AES256CMAC_KDF_USER_INPUT_PASSWORD_IN_BYTES 16
#define META_DATA_SIZE 64 // for Secure Storage tests
#define SECUREFS_HMAC_AES256CMAC_BLOCK_SIZE_IN_BYTES 16
#define HASH_DIGEST_SIZE_SHA256 32
#define AES_128_BLOCK_SIZE 16

void Initialize_SecureFs_Demo(void);
