CONFIG_FREERTOS_PLUS_POSIX=y
CONFIG_FTM_MODE=y
CONFIG_6G_BAND=y
CONFIG_LWIP_HEAP_POOL=y
CONFIG_XO_USE_BDF_OVERRIDE=n
CONFIG_SAT_STEP_MANUAL_ADJUSTMENT=n
# CONFIG_SAT_STEP_2G_SS=0x00000060
# CONFIG_SAT_STEP_2G_TT=0x00000060
# CONFIG_SAT_STEP_2G_FF=0x00000064
# CONFIG_SAT_STEP_5G_SS=0x00000064
# CONFIG_SAT_STEP_5G_TT=0x00000064
# CONFIG_SAT_STEP_5G_FF=0x00000064