#
# matter_demo setting
#
CONFIG_QCCSDK_DEMO=y
CONFIG_QCCSDK_CONSOLE=y
CONFIG_FREERTOS_PLUS_POSIX=y

CONFIG_PLATFORM_SHELL=y
CONFIG_WIFI_SHELL=n
CONFIG_LOWPOWER_SHELL=y
CONFIG_NET_SHELL=y
CONFIG_WLAN_QAPI=y
CONFIG_LWIP_HEAP_POOL=y

CONFIG_WATCH_DOG_ENABLE=n
CONFIG_WATCH_DOG_BITE_TIME=8
CONFIG_FW_UPGRADE=y
CONFIG_MBEDTLS_USE_PKA=y
CONFIG_MBEDTLS_PKA_TEST=n
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_POSIX_FS_API=y
CONFIG_FS_SHELL=y

CONFIG_NET_SSL_DEMO=n
CONFIG_MATTER_ENABLE=y
CONFIG_GENERATE_MATTER_LIB=y
CONFIG_MATTER_SWITCH_DEMO=n
CONFIG_MPU_ENABLE=n
# end of qcli_demo setting
