CONFIG_QCCSDK_CONSOLE = y // ruf die UART / Shell, ohne die hat man keine output
CONFIG_QCCSDK_DEMO = y // sagt die firmwares main.c das mein code gerufen wird muss bzw laufen lasse
CONFIG_WLAN_QAPI = y // ruft die wlan driver 
CONFIG_MQTT_CLIENT = y // pullt die MQTT clinet 