
#
# qat_demo setting
#
CONFIG_QCCSDK_DEMO=y
CONFIG_QCCSDK_CONSOLE=y
CONFIG_FLASH_SHELL=y
CONFIG_FREERTOS_PLUS_POSIX=y

CONFIG_WIFI_SHELL=y
CONFIG_WLAN_QAPI=y
CONFIG_PLATFORM_SHELL=y
CONFIG_LOWPOWER_SHELL=y
CONFIG_UNITTEST_SHELL=y
CONFIG_I2CM_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_NET_SHELL=y
CONFIG_UART_SHELL=y
CONFIG_LWIP_HEAP_POOL=y
CONFIG_6GHZ=y
CONFIG_6G_BAND=y
CONFIG_RTT_VIEW_CLI=y

CONFIG_WATCH_DOG_ENABLE=n
CONFIG_WATCH_DOG_BITE_TIME=8
CONFIG_FW_UPGRADE=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_POSIX_FS_API=y
CONFIG_FS_SHELL=y
CONFIG_MPU_DEMO=y
CONFIG_MQTT_CLIENT=y
CONFIG_MQTT_CLIENT_DEMO=y
#CONFIG_SIGMA_TRAFFIC=n
CONFIG_RING_IF_ONLY=n
CONFIG_QCSPI_HFC_TEST=n
CONFIG_QCSPI_HFC_ATCMD_ENABLE=n
CONFIG_HTTP_CLIENT=y
CONFIG_HTTP_CLIENT_DEMO=y
CONFIG_HTTP_SERVER=y
CONFIG_QAT_HTTP_SERVER_DEMO=y
CONFIG_RNG_TEST=y
CONFIG_SNTP_CLIENT=y
CONFIG_SNTP_CLIENT_DEMO=y
CONFIG_WIFI_FW_COREDUMP_SUPPORT=y
CONFIG_WIFI_FW_RAMDUMP_PRINT_FLAG=0

CONFIG_QAT=y
CONFIG_QAT_COMMON_DEMO=y
CONFIG_QAT_TRANSMISSION_MODULE=0
CONFIG_QAT_TCPIP_DEMO=y
CONFIG_QAT_MQTT_DEMO=y
CONFIG_QAT_WLAN_DEMO=y
CONFIG_QAT_HTTPC_DEMO=y
CONFIG_QAT_OTA_DEMO=y
CONFIG_QAT_FSTORE_DEMO=y
CONFIG_QAT_POWERSAVE_DEMO=y
CONFIG_QAT_CB_SIZE_MTU_MULTIPLIER=10
CONFIG_QAT_CB_QUEUE_MAX_LENGTH=10
CONFIG_WPS=y
CONFIG_WPS_LIB=y
# end of qat_demo setting

